FLASK_APP = main.py
FLASK_SECRET_KEY = "MySecretKey"
FLASK_DEBUG = True
FLASK_SQLALCHEMY_DATABASE_URI = sqlite:///db.sqlite3
FLASK_SQLALCHEMY_ECHO = False
FLASK_JWT_SECRET_KEY = 55636ca23ddfec580723bcb4