"""empty message

Revision ID: 01c0d731979b
Revises: b0f1c513bd6c
Create Date: 2024-07-20 15:23:15.860450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01c0d731979b'
down_revision = 'b0f1c513bd6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('path',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('path',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###
