"""empty message

Revision ID: 01c72f6ca83e
Revises: ad3f8c9797ef
Create Date: 2024-07-29 17:52:07.330311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01c72f6ca83e'
down_revision = 'ad3f8c9797ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('librarian')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('librarian', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###
