"""empty message

Revision ID: 14319f00c0f1
Revises: e6cf8932ff5c
Create Date: 2024-03-20 21:42:26.797806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14319f00c0f1'
down_revision = 'e6cf8932ff5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_request')
    # ### end Alembic commands ###
