"""empty message

Revision ID: 46ded47da443
Revises: 788cfbfd04d6
Create Date: 2024-07-29 17:43:31.600589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ded47da443'
down_revision = '788cfbfd04d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('librarian')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('librarian', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
