"""empty message

Revision ID: 4f68cdb020ca
Revises: 14319f00c0f1
Create Date: 2024-03-23 12:40:11.789979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f68cdb020ca'
down_revision = '14319f00c0f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_request', schema=None) as batch_op:
        batch_op.drop_column('requested_at')

    # ### end Alembic commands ###
