"""empty message

Revision ID: 82764c882282
Revises: f1d3cd176d8c
Create Date: 2024-07-20 22:15:09.368504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82764c882282'
down_revision = 'f1d3cd176d8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
