"""empty message

Revision ID: b930f60ff779
Revises: 4ceb8cb7246a
Create Date: 2024-07-29 17:54:21.399843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b930f60ff779'
down_revision = '4ceb8cb7246a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('librarian')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('librarian', sa.SMALLINT(), nullable=True))

    # ### end Alembic commands ###
