"""empty message

Revision ID: e1c5682f9228
Revises: 4f68cdb020ca
Create Date: 2024-04-01 21:05:58.980166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c5682f9228'
down_revision = '4f68cdb020ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', sa.String(length=128), nullable=True))

    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.alter_column('desc',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=32),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.alter_column('desc',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=128),
               nullable=False)

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('desc')

    # ### end Alembic commands ###
