"""empty message

Revision ID: e6cf8932ff5c
Revises: c0e6cd3b0a1d
Create Date: 2024-03-07 23:09:53.264712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6cf8932ff5c'
down_revision = 'c0e6cd3b0a1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('copies', sa.Integer(), nullable=False),
    sa.Column('issued', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_issue')
    op.drop_table('book')
    # ### end Alembic commands ###
