"""empty message

Revision ID: f1d3cd176d8c
Revises: 01c0d731979b
Create Date: 2024-07-20 15:33:25.792429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d3cd176d8c'
down_revision = '01c0d731979b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=128), nullable=True))
        batch_op.drop_column('path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
